### PR TITLE
State Transition Failed Event

### PR DESCRIPTION
**Pull request by LukeAvery92**
Added an event to observe when the FSM fails to enter a state.

### CODE REVIEW

**Review by FenrirWillow — CHANGES_REQUESTED** [review]
I do not agree that this should be a feature within the library. This is essentially soft exceptions except worse.

A FSM should not have invalid states. There should be no recovery from an invalid transition.

I'd like to hear more from you guys on why this should be included and why is it useful.

**Comment by LukeAvery92** [comment]
@FenrirWillow Failed is a misnomer. More the state change was requested but the conditional failed.

In the finite state example you cannot close the door if blocked is true. This case exists in the API already. This PR simply gives you access to observe that happening.

**Comment by LukeAvery92** [comment]
@FenrirWillow On an example why we would have failed states. Take for example a Animation state machine.

The character cannot be in a run state while jumping is true for example.

**Comment by FenrirWillow** [comment]
I am still unsure if I like this or not. Adding handlers for the `false`/`failed` branch leads to essentially very very complicated `if`/`else` statements. But I can see some use cases although a FSM would not be my first choice of abstraction there anyway.

**Comment by LukeAvery92** [comment]
@FenrirWillow understood, atm there is no way to know if a state transition has failed but it can happen. I would recommend this to be used when debugging needs to take place.

**Comment by kkjamie** [comment]
I tend to agree with @FenrirWillow with this. Let me understand a bit more. What was your motivation in adding this @LukeAvery92 ?

**Comment by LukeAvery92** [comment]
@kkjamie a transition failed and I wanted to know the details.

**Comment by kkjamie** [comment]
What details? And why did you want to know this. I'm trying to see the motivation & use cases

**Comment by LukeAvery92** [comment]
@kkjamie I was building a observer that tracked the history of a state machine. I was unable to know when a state machine failed to transition.

**Comment by LukeAvery92** [comment]
I have spoken with @kkjamie and came to same conclusion. My use case is longer needed and this PR doesnt solve anything or add any new functionality required by anyone.

Closing this PR

**Comment by LukeAvery92** [comment]
Deleting remote branch.

**Pull request closed without merging**
